spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:test'
    username: sa
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true


  thymeleaf:
    prefix: classpath:templates/
    check-template-location: true


logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace
